stages:
   - preamble
   - test
   - build
   - deploy

# WARNING: Remember to change the TAG based on the branch: master -> stable, develop -> latest, any-other-branch -> latest
variables:
   TAG: stable
   GIT_STRATEGY: clone

before_script:
    - bash /root/dls_gitlab_ci/gitlab-script.sh

preamble:
  image: server-dev:5000/dls-env:$TAG
  stage: preamble
  script:
    - bash /root/dls_gitlab_ci/gitlab-preamble.sh
  artifacts:
    paths:
      - version
      - release

build:
  image: server-dev:5000/dls-env:$TAG
  stage: build
  script:
    - source version
    - bash /root/dls_gitlab_ci/gitlab-bloom.sh $VERSION
  artifacts:
    paths:
      - "/builds/dls-lab/$CI_PROJECT_NAME/catkin_workspace/src/*.deb"

deploy:
  image: server-dev:5000/dls-env:$TAG
  stage: deploy
  script:
    - bash /root/dls_gitlab_ci/gitlab-deployment.sh
  environment:
    name: server-dev
    url: http://server-dev/debs
  only:
  - master
  - develop


